"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_page from './home-page.bones.json'
import _documents_page from './documents-page.bones.json'
import _players_page from './players-page.bones.json'
import _events_page from './events-page.bones.json'
import _news_page from './news-page.bones.json'

registerBones({
  "home-page": _home_page,
  "documents-page": _documents_page,
  "players-page": _players_page,
  "events-page": _events_page,
  "news-page": _news_page,
})
